version: '3.5'

services:
  db:
    image: mongo
    container_name: book-store-db-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  mongo-seed:
    build: './src/main/docker/db'
    links:
      - db

  api:
    build: .
    container_name: book-store-api-mongo
    environment:
      HOST: "db"
      USERNAME: "root"
      PASSWORD: "example"
      AUTHSOURCE: "admin"
      DB_NAME: "books-store"
      HTTP_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
      - mongo-seed

networks:
  default:
    external:
      name: book-store-network